// Mocked API layer for prototype/demo use.
// This lets the frontend work even if the real Python backend is not running.

export async function fetchRisk(contractAddress){
  // Simulate network latency
  await new Promise(resolve => setTimeout(resolve, 600))

  // Deterministic pseudo-score based on address so it "looks" realistic
  let score = 0.42
  try{
    if(contractAddress && contractAddress.length >= 6){
      const slice = contractAddress.replace(/^0x/i, '').slice(0, 4) || '1a2b'
      const n = parseInt(slice, 16)
      if(!Number.isNaN(n)){
        score = (n % 100) / 100
      }
    }
  }catch(e){
    score = 0.42
  }

  let risk_label = 'safe'
  if(score > 0.7) risk_label = 'dangerous'
  else if(score > 0.4) risk_label = 'caution'

  return {
    contract_address: contractAddress,
    risk_score: score,
    risk_label,
    ipfs_cid: 'QmMockedEvidenceCid123456789',
    feature_details: {
      reentrancy: score > 0.6,
      unchecked_calls: score > 0.5,
      centralization_risk: score > 0.4,
      external_calls: true,
      raw: {
        control_flow: {
          summary: 'Mocked control-flow analysis for prototype demo.',
          notes: [
            'No verified vulnerabilities – this is sample data.',
            'In a full deployment, this section is generated by the analysis_service.',
          ],
        },
      },
    },
    explanation:
      'This is a mocked risk assessment used for the prototype. The production backend will replace this with real model + static analysis results.',
    source: 'mock_backend',
  }
}

export async function fetchHistory(contractAddress){
  // Simple mocked history: three past assessments with varying scores
  await new Promise(resolve => setTimeout(resolve, 300))

  const base = (Date.now() / 1000) | 0
  return {
    contract_address: contractAddress,
    entries: [
      {
        timestamp: base - 72 * 3600,
        risk_score: 0.3,
        risk_label: 'safe',
        ipfs_cid: 'QmHistoryMockCid1',
      },
      {
        timestamp: base - 48 * 3600,
        risk_score: 0.55,
        risk_label: 'caution',
        ipfs_cid: 'QmHistoryMockCid2',
      },
      {
        timestamp: base - 24 * 3600,
        risk_score: 0.8,
        risk_label: 'dangerous',
        ipfs_cid: 'QmHistoryMockCid3',
      },
    ],
    source: 'mock_backend',
  }
}
